name: Deploy

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # ---------- build ----------
      - name: Setup node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "18.17.1"
          cache: "yarn"
      - name: Install requirements
        run: yarn install
      - name: Build
        run: yarn build
      # ---------- publish ----------
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID}}
          projectName: calculator
          directory: dist/spa
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
